name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Check test env 👮
        run: gh auth status
      - name: Test 🧪
        run: go test -v
      - name: Examine code 🔍
        run: go vet
      - name: Build 🏭
        run: go build main.go